kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: smackapi-deploy
spec:
  replicas: 3
  template: 
    metadata:
      labels:
        app: smackapi
    spec:
      containers:
      - name: smackapi
        image: chzbrgr71/smackapi
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8081
---
kind: Service
apiVersion: v1
metadata:
  name: smackapi
spec:
  selector:
    app: smackapi
  type: ClusterIP  
  ports:
  - name: http
    port: 8081
    targetPort: 8081